import asyncio
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        pg = await b.new_page(viewport={"width":1700,"height":950})
        errs=[]; pg.on("pageerror", lambda e: errs.append(str(e)))
        await pg.goto(__import__("os").environ.get("BASE_URL","http://localhost:4173/"))
        await pg.wait_for_timeout(500)
        await pg.get_by_role("button", name="Manage Products").first.click()
        await pg.wait_for_timeout(500)
        dot = lambda: pg.evaluate("[...document.querySelectorAll('[role=tab]')].map(t=>t.textContent.trim()+':'+!!t.querySelector('.tab-dot'))")
        print("start", await dot())
        await pg.get_by_role("button", name="Create Mapping").click()
        await pg.wait_for_timeout(500)
        await pg.locator('#f-cycle').click(); await pg.locator('li[role=option]', has_text="O").first.click()
        await pg.locator('#f-projectType').click(); await pg.locator('li[role=option]').nth(2).click()
        await pg.wait_for_timeout(300)
        await pg.locator('#f-personnel').click(); await pg.locator('li[role=option]').first.click(); await pg.keyboard.press("Escape")
        await pg.wait_for_timeout(300)
        await pg.screenshot(path="/tmp/shot_td1.png")
        await pg.locator('[id="fam-Category A"]').click(); await pg.locator('li[role=option]').first.click(); await pg.keyboard.press("Escape")
        await pg.get_by_role("button", name="Create", exact=True).click()
        await pg.wait_for_timeout(700)
        for i in range(2):
            if await pg.locator(".confirm-paper").count(): await pg.get_by_role("button", name="Create", exact=True).last.click(); await pg.wait_for_timeout(600)
        print("after create", await dot())
        await pg.get_by_role("tab", name="Schedule").click(); await pg.wait_for_timeout(800)
        print("opened Schedule", await dot())
        await pg.get_by_role("tab", name="Mapping").click(); await pg.wait_for_timeout(500)
        print("back to Mapping", await dot())
        await pg.get_by_role("tab", name="Schedule").click(); await pg.wait_for_timeout(800)
        await pg.get_by_role("button", name="Activity Type").click(); await pg.wait_for_timeout(700)
        n = await pg.locator(".ag-pinned-left-cols-container .ag-row").count()
        for i in range(n):
            await pg.locator(".ag-pinned-left-cols-container .ag-row").nth(i).locator('[col-id=projectType]').click(); await pg.wait_for_timeout(250)
            print("clicked row", i, await dot())
        await b.close()
asyncio.run(main())
